### ISSUE TITLE
How to controle 8 Channel Relay 

### ISSUE THREAD

**Issue by ranvirgorai** [forkineye/ESPAsyncE131#11]
I need help to create **8 channel** relay switch board using this library, want to controle those relay using **Xlights**.
Using example code I am able to recieve data from xlights to **nodemcu** in serial monitor. any one can provide code to run on nodemcu  code to controle 8 channel relay and it would be great if you can suggest any framework for the same.

Thank you

**Comment by forkineye** [comment]
For a reference implementation, please refer to the ESPixelStick project - https://github.com/forkineye/ESPixelStick
