### ISSUE TITLE
user_interface.h not found when building for Esp32 on platformio

### ISSUE THREAD

**Issue by Munger** [forkineye/ESPAsyncE131#14]
When building on VSCode I get the error:

.pio\libdeps\FastLEDVirtual_5-Pin\ESPAsyncUDP\src\AsyncUDP.cpp:5:28: fatal error: user_interface.h: No such file or directory

Any suggestions?

**Comment by Munger** [comment]
False alarm. PlatformIO pulled in the ESP8266 ESPAsyncUDP library as a dependency instead of using the one built in.

**Comment by jxsavage** [comment]
@Munger How were you able to get PlatformIO to pull the correct dependency? I'm having this issue on my laptop but not on my desktop and I'm not sure how to resolve it. Thanks.

**Comment by Munger** [comment]
I don’t really remember, but I probably uninstalled the ESP8266 libraries.
