### ISSUE TITLE
7 second delay

### ISSUE THREAD

**Issue by tresler** [forkineye/ESPAsyncE131#17]
I try doing sACN receiver by this and ESP32-S2, but I have 7 second delay on local network. I try to do on ethernet with W5500 (on ESPAsyncE131.h change #ifdef ESP32 #include <Ethernet.h> #include <EthernetUdp.h> #include <AsyncUDP.h> and some change in example code) and everything works fine (with one restart), but also I have 7 second delay from my lightpost. Where can be the mistake?

**Comment by forkineye** [comment]
The W5500 is an SPI Ethernet controller. The ESP32 has it's own Ethernet MAC. I you're wanting to do Ethernet on ESP32, I'd recommend implementing the Ethernet PHY for it and getting away from the W5500.
