### ISSUE TITLE
Increase number of output pixel with parallel output in Esp-12e.

### ISSUE THREAD

**Issue by Kamal-Sonani** [forkineye/ESPAsyncE131#2]
What about parallel output such as arduino UNO's ports in esp8266(12e)?

If single pin can handle 700 led so far on Esp 01, is it possible to manage more pixel using parallel output?

According UDP connections data processing and FPS nearly about 25 to 30.

**Comment by forkineye** [comment]
This library is solely for the processing of E1.31 data.   Implementation is up to the user, be it pixels, DMX output, driving servos, or whatever they want to use it for.
