### ISSUE TITLE
ethernet fail

### ISSUE THREAD

**Issue by colarocker** [forkineye/ESPAsyncE131#5]
Can someone give me a clue how to use this with ethernet? i am using a w5500 shield, fixed ip-adress (ping-able). the multicast won't start with e131.begin(E131_MULTICAST, UNIVERSE, UNIVERSE_COUNT);
in Async_UDP, it uses igmp_joingroup, which returns a ESP_ERR_INVALID_STATE, that's what i found out so far. I don't know where to look now :/ Help is appreciated.

for better understanding: inside the initMulticast function, i changed this line: ifaddr.addr = static_cast<uint32_t>(Ethernet.localIP());  so it uses the ethernet ip instead of the wifi one. sadly it's not enough.

**Comment by forkineye** [comment]
You'll have to write your own wrappers to support wiznet modules.
