### ISSUE TITLE
Locks up on the ESP32

### ISSUE THREAD

**Issue by computergeek1507** [forkineye/ESPAsyncE131#8]
On the ESP32 the library will stop reading packets after a while. With one universe in unicast mode it happens randomly. With 10 universes it stops immediately. I tried increasing the buffer slots to 30 and it will stop receiving packets when I send 4 universes of data from xLights. I am using the ESP32 1.3 rc1 ardunio core with a manual edit to the "AsyncUDP.cpp" library to workaround the issue described here https://github.com/espressif/arduino-esp32/issues/2685

Thanks,
Scott

**Comment by forkineye** [comment]
Are you still having issues with this or was related to the core?

**Comment by computergeek1507** [comment]
I still get this but I have abandoned all my ESP32 development for now. It happens when I send 4+ universes of data, I think the stack will overflow but it may be a issue with my code.

**Comment by ayufan** [comment]
I think that this code is not thread-safe. This is why you see this problem.
